//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3521
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tawala.DesignerUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tawala.DesignerUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon App {
            get {
                object obj = ResourceManager.GetObject("App", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlockBackButtonTrue {
            get {
                object obj = ResourceManager.GetObject("BlockBackButtonTrue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to add a new {0}.
        /// </summary>
        internal static string ClickCreateNew {
            get {
                return ResourceManager.GetString("ClickCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Data Source Name Here.
        /// </summary>
        internal static string DefaultDataSourceNameText {
            get {
                return ResourceManager.GetString("DefaultDataSourceNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project deployment failed:.
        /// </summary>
        internal static string DeployFailure {
            get {
                return ResourceManager.GetString("DeployFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to view selected Form.
        /// </summary>
        internal static string DeploymentLinkText {
            get {
                return ResourceManager.GetString("DeploymentLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Project was successfully deployed..
        /// </summary>
        internal static string DeploySuccess {
            get {
                return ResourceManager.GetString("DeploySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may select a Form from the list below and click on the link to invoke it. You can also use the Invitation Manager to generate links for any of your deployed Forms at any time..
        /// </summary>
        internal static string DeploySuccess2 {
            get {
                return ResourceManager.GetString("DeploySuccess2", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Document {
            get {
                object obj = ResourceManager.GetObject("Document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Document_InTree {
            get {
                object obj = ResourceManager.GetObject("Document_InTree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Document_New {
            get {
                object obj = ResourceManager.GetObject("Document_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string DocumentString {
            get {
                return ResourceManager.GetString("DocumentString", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DownArrow {
            get {
                object obj = ResourceManager.GetObject("DownArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_Copy {
            get {
                object obj = ResourceManager.GetObject("Edit_Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_Cut {
            get {
                object obj = ResourceManager.GetObject("Edit_Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_Delete {
            get {
                object obj = ResourceManager.GetObject("Edit_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_Paste {
            get {
                object obj = ResourceManager.GetObject("Edit_Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_Redo {
            get {
                object obj = ResourceManager.GetObject("Edit_Redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_Undo {
            get {
                object obj = ResourceManager.GetObject("Edit_Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap File_Save {
            get {
                object obj = ResourceManager.GetObject("File_Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Folder_Closed {
            get {
                object obj = ResourceManager.GetObject("Folder_Closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Folder_Open {
            get {
                object obj = ResourceManager.GetObject("Folder_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Folder_OpenWithArrow {
            get {
                object obj = ResourceManager.GetObject("Folder_OpenWithArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Font_Bold {
            get {
                object obj = ResourceManager.GetObject("Font_Bold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Font_ChooseColor {
            get {
                object obj = ResourceManager.GetObject("Font_ChooseColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Font_ColorButtonDefault {
            get {
                object obj = ResourceManager.GetObject("Font_ColorButtonDefault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Font_ColorButtonTheme {
            get {
                object obj = ResourceManager.GetObject("Font_ColorButtonTheme", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Font_DefaultColor {
            get {
                object obj = ResourceManager.GetObject("Font_DefaultColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Font_Italic {
            get {
                object obj = ResourceManager.GetObject("Font_Italic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Font_ThemeColorSwatch {
            get {
                object obj = ResourceManager.GetObject("Font_ThemeColorSwatch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Font_Underline {
            get {
                object obj = ResourceManager.GetObject("Font_Underline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form {
            get {
                object obj = ResourceManager.GetObject("Form", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_BlockBackButton_Overlay {
            get {
                object obj = ResourceManager.GetObject("Form_BlockBackButton_Overlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_InTree {
            get {
                object obj = ResourceManager.GetObject("Form_InTree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_IsPrepopulated_Overlay {
            get {
                object obj = ResourceManager.GetObject("Form_IsPrepopulated_Overlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_IsStartPoint {
            get {
                object obj = ResourceManager.GetObject("Form_IsStartPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_IsStartPoint_Overlay {
            get {
                object obj = ResourceManager.GetObject("Form_IsStartPoint_Overlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_ItemBreak {
            get {
                object obj = ResourceManager.GetObject("Form_ItemBreak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_ItemDragInsert {
            get {
                object obj = ResourceManager.GetObject("Form_ItemDragInsert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_ItemFib {
            get {
                object obj = ResourceManager.GetObject("Form_ItemFib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_ItemHeading {
            get {
                object obj = ResourceManager.GetObject("Form_ItemHeading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_ItemHiddenField {
            get {
                object obj = ResourceManager.GetObject("Form_ItemHiddenField", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_ItemMcq {
            get {
                object obj = ResourceManager.GetObject("Form_ItemMcq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_ItemSkip {
            get {
                object obj = ResourceManager.GetObject("Form_ItemSkip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_ItemText {
            get {
                object obj = ResourceManager.GetObject("Form_ItemText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_LastRecord {
            get {
                object obj = ResourceManager.GetObject("Form_LastRecord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_MakeStartPoint {
            get {
                object obj = ResourceManager.GetObject("Form_MakeStartPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_New {
            get {
                object obj = ResourceManager.GetObject("Form_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_PostProcess {
            get {
                object obj = ResourceManager.GetObject("Form_PostProcess", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_PreProcess {
            get {
                object obj = ResourceManager.GetObject("Form_PreProcess", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_Preview {
            get {
                object obj = ResourceManager.GetObject("Form_Preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        internal static string FormString {
            get {
                return ResourceManager.GetString("FormString", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Function {
            get {
                object obj = ResourceManager.GetObject("Function", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help_Information {
            get {
                object obj = ResourceManager.GetObject("Help_Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load ValidationFunction definitions. The Tawala server may not be available. Please exit the application and try again later..
        /// </summary>
        internal static string InitializationTasksError {
            get {
                return ResourceManager.GetString("InitializationTasksError", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Insert_Image {
            get {
                object obj = ResourceManager.GetObject("Insert_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InsertMarker {
            get {
                object obj = ResourceManager.GetObject("InsertMarker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Tawala file. Selected file cannot be read by this version of Tawala..
        /// </summary>
        internal static string InvalidFileError {
            get {
                return ResourceManager.GetString("InvalidFileError", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap InvitationManager {
            get {
                object obj = ResourceManager.GetObject("InvitationManager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Module.
        /// </summary>
        internal static string ModuleString {
            get {
                return ResourceManager.GetString("ModuleString", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MoveNext {
            get {
                object obj = ResourceManager.GetObject("MoveNext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MovePrevious {
            get {
                object obj = ResourceManager.GetObject("MovePrevious", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project was created with a newer version of the Tawala Project Designer. You need to update your version of the application  in order to open it..
        /// </summary>
        internal static string NewerXmlFormatVersion {
            get {
                return ResourceManager.GetString("NewerXmlFormatVersion", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap NormalView {
            get {
                object obj = ResourceManager.GetObject("NormalView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tawala Project Files (*.tawala)|*.tawala|Tawala XML Files (*.xml)|*.xml.
        /// </summary>
        internal static string OpenProjectFilter {
            get {
                return ResourceManager.GetString("OpenProjectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image - {0} x {1}.
        /// </summary>
        internal static string PageHeaderImageInfo {
            get {
                return ResourceManager.GetString("PageHeaderImageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files (*.gif; *.jpg; *.png;) | *.gif; *.jpg; *.png;.
        /// </summary>
        internal static string PageHeaderOpenImageFilter {
            get {
                return ResourceManager.GetString("PageHeaderOpenImageFilter", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PageView {
            get {
                object obj = ResourceManager.GetObject("PageView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Paragraph_Indent {
            get {
                object obj = ResourceManager.GetObject("Paragraph_Indent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Paragraph_Outdent {
            get {
                object obj = ResourceManager.GetObject("Paragraph_Outdent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prepopulate {
            get {
                object obj = ResourceManager.GetObject("Prepopulate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Process {
            get {
                object obj = ResourceManager.GetObject("Process", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Process_InTree {
            get {
                object obj = ResourceManager.GetObject("Process_InTree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Process_New {
            get {
                object obj = ResourceManager.GetObject("Process_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string ProcessString {
            get {
                return ResourceManager.GetString("ProcessString", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Project {
            get {
                object obj = ResourceManager.GetObject("Project", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Project_Deploy {
            get {
                object obj = ResourceManager.GetObject("Project_Deploy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Project_Manager {
            get {
                object obj = ResourceManager.GetObject("Project_Manager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Project_New {
            get {
                object obj = ResourceManager.GetObject("Project_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tawala.
        /// </summary>
        internal static string ProjectExt {
            get {
                return ResourceManager.GetString("ProjectExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project not found!.
        /// </summary>
        internal static string ProjectNotFound {
            get {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xml.
        /// </summary>
        internal static string ProjectXmlExt {
            get {
                return ResourceManager.GetString("ProjectXmlExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project may have changed.  Do you want to save the changes?.
        /// </summary>
        internal static string SaveOnExitNewLoadMessage {
            get {
                return ResourceManager.GetString("SaveOnExitNewLoadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save project file.
        /// </summary>
        internal static string SaveProjectFailureCaption {
            get {
                return ResourceManager.GetString("SaveProjectFailureCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tawala Project Files (*.tawala)|*.tawala.
        /// </summary>
        internal static string SaveProjectFilter {
            get {
                return ResourceManager.GetString("SaveProjectFilter", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SizeToContents {
            get {
                object obj = ResourceManager.GetObject("SizeToContents", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StartPointLastRecord {
            get {
                object obj = ResourceManager.GetObject("StartPointLastRecord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag Form items to move them.  Right click on label to display context menu..
        /// </summary>
        internal static string StatusBarFormItem {
            get {
                return ResourceManager.GetString("StatusBarFormItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add a new item, drag it from the Palette to the Form..
        /// </summary>
        internal static string StatusBarFormView {
            get {
                return ResourceManager.GetString("StatusBarFormView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click on Project pane items to display a context menu..
        /// </summary>
        internal static string StatusBarProjectPane {
            get {
                return ResourceManager.GetString("StatusBarProjectPane", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Table_AddColumnAfter {
            get {
                object obj = ResourceManager.GetObject("Table_AddColumnAfter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_AddColumnBefore {
            get {
                object obj = ResourceManager.GetObject("Table_AddColumnBefore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_AddRowAfter {
            get {
                object obj = ResourceManager.GetObject("Table_AddRowAfter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_AddRowBefore {
            get {
                object obj = ResourceManager.GetObject("Table_AddRowBefore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_Delete {
            get {
                object obj = ResourceManager.GetObject("Table_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_DeleteColumn {
            get {
                object obj = ResourceManager.GetObject("Table_DeleteColumn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_DeleteRow {
            get {
                object obj = ResourceManager.GetObject("Table_DeleteRow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_Insert {
            get {
                object obj = ResourceManager.GetObject("Table_Insert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_InsertDeleteRowOrColumn {
            get {
                object obj = ResourceManager.GetObject("Table_InsertDeleteRowOrColumn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Text_Center {
            get {
                object obj = ResourceManager.GetObject("Text_Center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Text_ClearFormatting {
            get {
                object obj = ResourceManager.GetObject("Text_ClearFormatting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Text_Justify {
            get {
                object obj = ResourceManager.GetObject("Text_Justify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Text_LeftAlign {
            get {
                object obj = ResourceManager.GetObject("Text_LeftAlign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Text_RightAlign {
            get {
                object obj = ResourceManager.GetObject("Text_RightAlign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ValidationFunction {
            get {
                object obj = ResourceManager.GetObject("ValidationFunction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View {
            get {
                object obj = ResourceManager.GetObject("View", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown during the web request:.
        /// </summary>
        internal static string WebRequestExceptionThrown {
            get {
                return ResourceManager.GetString("WebRequestExceptionThrown", resourceCulture);
            }
        }
    }
}
