hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://localhost/tawala
hibernate.connection.username=tawala_user
hibernate.connection.password=tawala
#  READ_COMMITTED
hibernate.connection.isolation=2

hibernate.cache.provider_class=org.hibernate.cache.HashtableCacheProvider
hibernate.format_sql=false
hibernate.use_sql_comments=false
