//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tawala.FormDesigner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tawala.FormDesigner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Fill in the Blank questions are selected in the active form. You may apply the style to all Fill in the Blank questions in the project..
        /// </summary>
        internal static string ApplyStyleToAllFIBItems {
            get {
                return ResourceManager.GetString("ApplyStyleToAllFIBItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Multiple Choice questions are selected in the active form. You may apply the style to all Multiple Choice questions in the project..
        /// </summary>
        internal static string ApplyStyleToAllMCQItems {
            get {
                return ResourceManager.GetString("ApplyStyleToAllMCQItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Text items are selected in the active form. You may apply the style to all Text items in the project..
        /// </summary>
        internal static string ApplyStyleToAllTextItems {
            get {
                return ResourceManager.GetString("ApplyStyleToAllTextItems", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Bold {
            get {
                object obj = ResourceManager.GetObject("Bold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Document_New {
            get {
                object obj = ResourceManager.GetObject("Document_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_Copy {
            get {
                object obj = ResourceManager.GetObject("Edit_Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_Cut {
            get {
                object obj = ResourceManager.GetObject("Edit_Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_Delete {
            get {
                object obj = ResourceManager.GetObject("Edit_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_Paste {
            get {
                object obj = ResourceManager.GetObject("Edit_Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_Redo {
            get {
                object obj = ResourceManager.GetObject("Edit_Redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_Undo {
            get {
                object obj = ResourceManager.GetObject("Edit_Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Folder_Open {
            get {
                object obj = ResourceManager.GetObject("Folder_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Font_ChooseColor {
            get {
                object obj = ResourceManager.GetObject("Font_ChooseColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Font_ColorButtonTheme {
            get {
                object obj = ResourceManager.GetObject("Font_ColorButtonTheme", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Font_DefaultColor {
            get {
                object obj = ResourceManager.GetObject("Font_DefaultColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Font_ThemeColorSwatch {
            get {
                object obj = ResourceManager.GetObject("Font_ThemeColorSwatch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_ItemBreak {
            get {
                object obj = ResourceManager.GetObject("Form_ItemBreak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_ItemFib {
            get {
                object obj = ResourceManager.GetObject("Form_ItemFib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_ItemHeading {
            get {
                object obj = ResourceManager.GetObject("Form_ItemHeading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_ItemHiddenField {
            get {
                object obj = ResourceManager.GetObject("Form_ItemHiddenField", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_ItemMcq {
            get {
                object obj = ResourceManager.GetObject("Form_ItemMcq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_ItemSkip {
            get {
                object obj = ResourceManager.GetObject("Form_ItemSkip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_ItemText {
            get {
                object obj = ResourceManager.GetObject("Form_ItemText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_ItemTextarea {
            get {
                object obj = ResourceManager.GetObject("Form_ItemTextarea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_New {
            get {
                object obj = ResourceManager.GetObject("Form_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Form Preview&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		body { font: 14pt Arial Bold; color: blue; }
        ///    &lt;/style&gt;
        ///
        ///	&lt;script type=&quot;text/javascript&quot;&gt;
        ///		function onRefreshClicked()
        ///		{
        ///			window.external.HTMLRefreshButton_Clicked();
        ///		}
        ///	&lt;/script&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;div style=&quot;text-align: center;&quot;&gt;
        ///		&lt;p&gt;
        ///			&amp;nbsp;&lt;/p&gt;
        ///		&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FormPreviewException {
            get {
                return ResourceManager.GetString("FormPreviewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Form Preview&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		body { font: 14pt Arial Bold; color: blue; }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;div style=&quot;text-align: center;&quot;&gt;
        ///	Generating form preview...
        ///	&lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string FormPreviewGenerating {
            get {
                return ResourceManager.GetString("FormPreviewGenerating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Form Preview&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		body { font: 14pt Arial Bold; color: blue; }
        ///    &lt;/style&gt;
        ///
        ///	&lt;script type=&quot;text/javascript&quot;&gt;
        ///		function onRefreshClicked()
        ///		{
        ///			window.external.HTMLRefreshButton_Clicked();
        ///		}
        ///	&lt;/script&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;div style=&quot;text-align: center;&quot;&gt;
        ///		&lt;p&gt;
        ///			&amp;nbsp;&lt;/p&gt;
        ///		&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FormPreviewRefresh1 {
            get {
                return ResourceManager.GetString("FormPreviewRefresh1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Form Preview&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		body { font: 14pt Arial Bold; color: blue; }
        ///    &lt;/style&gt;
        ///
        ///	&lt;script type=&quot;text/javascript&quot;&gt;
        ///		function onRefreshClicked()
        ///		{
        ///			window.external.HTMLRefreshButton_Clicked();
        ///		}
        ///	&lt;/script&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;div style=&quot;text-align: center;&quot;&gt;
        ///		&lt;p&gt;
        ///			&amp;nbsp;&lt;/p&gt;
        ///		&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FormPreviewRefresh2 {
            get {
                return ResourceManager.GetString("FormPreviewRefresh2", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Function {
            get {
                object obj = ResourceManager.GetObject("Function", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Insert_Image {
            get {
                object obj = ResourceManager.GetObject("Insert_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InsertHyperlink {
            get {
                object obj = ResourceManager.GetObject("InsertHyperlink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Italic {
            get {
                object obj = ResourceManager.GetObject("Italic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid blank label.
        /// </summary>
        internal static string OptionsInvalidBlankLabel {
            get {
                return ResourceManager.GetString("OptionsInvalidBlankLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid label.
        /// </summary>
        internal static string OptionsInvalidItemLabel {
            get {
                return ResourceManager.GetString("OptionsInvalidItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid question label.
        /// </summary>
        internal static string OptionsInvalidQuestionLabel {
            get {
                return ResourceManager.GetString("OptionsInvalidQuestionLabel", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Paragraph_Indent {
            get {
                object obj = ResourceManager.GetObject("Paragraph_Indent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Paragraph_Outdent {
            get {
                object obj = ResourceManager.GetObject("Paragraph_Outdent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Project_New {
            get {
                object obj = ResourceManager.GetObject("Project_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Project_Save {
            get {
                object obj = ResourceManager.GetObject("Project_Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_AddColumnAfter {
            get {
                object obj = ResourceManager.GetObject("Table_AddColumnAfter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_AddColumnBefore {
            get {
                object obj = ResourceManager.GetObject("Table_AddColumnBefore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_AddRowAfter {
            get {
                object obj = ResourceManager.GetObject("Table_AddRowAfter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_AddRowBefore {
            get {
                object obj = ResourceManager.GetObject("Table_AddRowBefore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_Delete {
            get {
                object obj = ResourceManager.GetObject("Table_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_DeleteColumn {
            get {
                object obj = ResourceManager.GetObject("Table_DeleteColumn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_DeleteRow {
            get {
                object obj = ResourceManager.GetObject("Table_DeleteRow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_Insert {
            get {
                object obj = ResourceManager.GetObject("Table_Insert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_InsertDeleteRowOrColumn {
            get {
                object obj = ResourceManager.GetObject("Table_InsertDeleteRowOrColumn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_ResizeColumn {
            get {
                object obj = ResourceManager.GetObject("Table_ResizeColumn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Text_Center {
            get {
                object obj = ResourceManager.GetObject("Text_Center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Text_ClearFormatting {
            get {
                object obj = ResourceManager.GetObject("Text_ClearFormatting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Text_Justify {
            get {
                object obj = ResourceManager.GetObject("Text_Justify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Text_LeftAlign {
            get {
                object obj = ResourceManager.GetObject("Text_LeftAlign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Text_RightAlign {
            get {
                object obj = ResourceManager.GetObject("Text_RightAlign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Underline {
            get {
                object obj = ResourceManager.GetObject("Underline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
