//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3521
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tawala.Forms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tawala.Forms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Fill in the Blank questions are selected in the active form. You may apply the style to all Fill in the Blank questions in the project..
        /// </summary>
        internal static string ApplyStyleToAllFIBItems {
            get {
                return ResourceManager.GetString("ApplyStyleToAllFIBItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Multiple Choice questions are selected in the active form. You may apply the style to all Multiple Choice questions in the project..
        /// </summary>
        internal static string ApplyStyleToAllMCQItems {
            get {
                return ResourceManager.GetString("ApplyStyleToAllMCQItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Text items are selected in the active form. You may apply the style to all Text items in the project..
        /// </summary>
        internal static string ApplyStyleToAllTextItems {
            get {
                return ResourceManager.GetString("ApplyStyleToAllTextItems", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Document_New {
            get {
                object obj = ResourceManager.GetObject("Document_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choices from stored data: OFF.
        /// </summary>
        internal static string DynamicMCQChoicesOff {
            get {
                return ResourceManager.GetString("DynamicMCQChoicesOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choices from stored data: ON.
        /// </summary>
        internal static string DynamicMCQChoicesOn {
            get {
                return ResourceManager.GetString("DynamicMCQChoicesOn", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Edit_Copy {
            get {
                object obj = ResourceManager.GetObject("Edit_Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_Cut {
            get {
                object obj = ResourceManager.GetObject("Edit_Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_Delete {
            get {
                object obj = ResourceManager.GetObject("Edit_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_Paste {
            get {
                object obj = ResourceManager.GetObject("Edit_Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_Redo {
            get {
                object obj = ResourceManager.GetObject("Edit_Redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_Undo {
            get {
                object obj = ResourceManager.GetObject("Edit_Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap File_Save {
            get {
                object obj = ResourceManager.GetObject("File_Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Folder_Closed {
            get {
                object obj = ResourceManager.GetObject("Folder_Closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Folder_Open {
            get {
                object obj = ResourceManager.GetObject("Folder_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Folder_OpenWithArrow {
            get {
                object obj = ResourceManager.GetObject("Folder_OpenWithArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Font_Bold {
            get {
                object obj = ResourceManager.GetObject("Font_Bold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Font_ChooseColor {
            get {
                object obj = ResourceManager.GetObject("Font_ChooseColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Font_ColorButtonDefault {
            get {
                object obj = ResourceManager.GetObject("Font_ColorButtonDefault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Font_ColorButtonTheme {
            get {
                object obj = ResourceManager.GetObject("Font_ColorButtonTheme", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Font_DefaultColor {
            get {
                object obj = ResourceManager.GetObject("Font_DefaultColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Font_Italic {
            get {
                object obj = ResourceManager.GetObject("Font_Italic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Font_ThemeColorSwatch {
            get {
                object obj = ResourceManager.GetObject("Font_ThemeColorSwatch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Font_Underline {
            get {
                object obj = ResourceManager.GetObject("Font_Underline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Form {
            get {
                object obj = ResourceManager.GetObject("Form", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_IsStartPoint {
            get {
                object obj = ResourceManager.GetObject("Form_IsStartPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_ItemBreak {
            get {
                object obj = ResourceManager.GetObject("Form_ItemBreak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_ItemDragInsert {
            get {
                object obj = ResourceManager.GetObject("Form_ItemDragInsert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_ItemFib {
            get {
                object obj = ResourceManager.GetObject("Form_ItemFib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_ItemHeading {
            get {
                object obj = ResourceManager.GetObject("Form_ItemHeading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_ItemHiddenField {
            get {
                object obj = ResourceManager.GetObject("Form_ItemHiddenField", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_ItemMcq {
            get {
                object obj = ResourceManager.GetObject("Form_ItemMcq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_ItemSkip {
            get {
                object obj = ResourceManager.GetObject("Form_ItemSkip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_ItemText {
            get {
                object obj = ResourceManager.GetObject("Form_ItemText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_LastRecord {
            get {
                object obj = ResourceManager.GetObject("Form_LastRecord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_MakeStartPoint {
            get {
                object obj = ResourceManager.GetObject("Form_MakeStartPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_New {
            get {
                object obj = ResourceManager.GetObject("Form_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_PostProcess {
            get {
                object obj = ResourceManager.GetObject("Form_PostProcess", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_PreProcess {
            get {
                object obj = ResourceManager.GetObject("Form_PreProcess", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_Preview {
            get {
                object obj = ResourceManager.GetObject("Form_Preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Form Preview&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		body { font: 14pt Arial Bold; color: blue; }
        ///    &lt;/style&gt;
        ///
        ///	&lt;script type=&quot;text/javascript&quot;&gt;
        ///		function onRefreshClicked()
        ///		{
        ///			window.external.HTMLRefreshButton_Clicked();
        ///		}
        ///	&lt;/script&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;div style=&quot;text-align: center;&quot;&gt;
        ///		&lt;p&gt;
        ///			&amp;nbsp;&lt;/p&gt;
        ///		&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FormPreviewException {
            get {
                return ResourceManager.GetString("FormPreviewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Form Preview&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		body { font: 14pt Arial Bold; color: blue; }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;div style=&quot;text-align: center;&quot;&gt;
        ///	Generating form preview...
        ///	&lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string FormPreviewGenerating {
            get {
                return ResourceManager.GetString("FormPreviewGenerating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Form Preview&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		body { font: 14pt Arial Bold; color: blue; }
        ///    &lt;/style&gt;
        ///
        ///	&lt;script type=&quot;text/javascript&quot;&gt;
        ///		function onRefreshClicked()
        ///		{
        ///			window.external.HTMLRefreshButton_Clicked();
        ///		}
        ///	&lt;/script&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;div style=&quot;text-align: center;&quot;&gt;
        ///		&lt;p&gt;
        ///			&amp;nbsp;&lt;/p&gt;
        ///		&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FormPreviewRefresh1 {
            get {
                return ResourceManager.GetString("FormPreviewRefresh1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Form Preview&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		body { font: 14pt Arial Bold; color: blue; }
        ///    &lt;/style&gt;
        ///
        ///	&lt;script type=&quot;text/javascript&quot;&gt;
        ///		function onRefreshClicked()
        ///		{
        ///			window.external.HTMLRefreshButton_Clicked();
        ///		}
        ///	&lt;/script&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;div style=&quot;text-align: center;&quot;&gt;
        ///		&lt;p&gt;
        ///			&amp;nbsp;&lt;/p&gt;
        ///		&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FormPreviewRefresh2 {
            get {
                return ResourceManager.GetString("FormPreviewRefresh2", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Function {
            get {
                object obj = ResourceManager.GetObject("Function", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help_Information {
            get {
                object obj = ResourceManager.GetObject("Help_Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Insert_Hyperlink {
            get {
                object obj = ResourceManager.GetObject("Insert_Hyperlink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Insert_Image {
            get {
                object obj = ResourceManager.GetObject("Insert_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field name contains a colon or other invalid character.
        /// </summary>
        internal static string InvalidFieldName {
            get {
                return ResourceManager.GetString("InvalidFieldName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap InvitationManager {
            get {
                object obj = ResourceManager.GetObject("InvitationManager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NormalView {
            get {
                object obj = ResourceManager.GetObject("NormalView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PageView {
            get {
                object obj = ResourceManager.GetObject("PageView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Paragraph_Indent {
            get {
                object obj = ResourceManager.GetObject("Paragraph_Indent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Paragraph_Outdent {
            get {
                object obj = ResourceManager.GetObject("Paragraph_Outdent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Process {
            get {
                object obj = ResourceManager.GetObject("Process", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Process_New {
            get {
                object obj = ResourceManager.GetObject("Process_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Project {
            get {
                object obj = ResourceManager.GetObject("Project", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Project_Deploy {
            get {
                object obj = ResourceManager.GetObject("Project_Deploy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Project_Manager {
            get {
                object obj = ResourceManager.GetObject("Project_Manager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Project_New {
            get {
                object obj = ResourceManager.GetObject("Project_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SizeToContents {
            get {
                object obj = ResourceManager.GetObject("SizeToContents", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StartPointLastRecord {
            get {
                object obj = ResourceManager.GetObject("StartPointLastRecord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_AddColumnAfter {
            get {
                object obj = ResourceManager.GetObject("Table_AddColumnAfter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_AddColumnBefore {
            get {
                object obj = ResourceManager.GetObject("Table_AddColumnBefore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_AddRowAfter {
            get {
                object obj = ResourceManager.GetObject("Table_AddRowAfter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_AddRowBefore {
            get {
                object obj = ResourceManager.GetObject("Table_AddRowBefore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_Delete {
            get {
                object obj = ResourceManager.GetObject("Table_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_DeleteColumn {
            get {
                object obj = ResourceManager.GetObject("Table_DeleteColumn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_DeleteRow {
            get {
                object obj = ResourceManager.GetObject("Table_DeleteRow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_Insert {
            get {
                object obj = ResourceManager.GetObject("Table_Insert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_InsertDeleteRowOrColumn {
            get {
                object obj = ResourceManager.GetObject("Table_InsertDeleteRowOrColumn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Text_Center {
            get {
                object obj = ResourceManager.GetObject("Text_Center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Text_ClearFormatting {
            get {
                object obj = ResourceManager.GetObject("Text_ClearFormatting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Text_Justify {
            get {
                object obj = ResourceManager.GetObject("Text_Justify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Text_LeftAlign {
            get {
                object obj = ResourceManager.GetObject("Text_LeftAlign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Text_RightAlign {
            get {
                object obj = ResourceManager.GetObject("Text_RightAlign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UploadToWeb {
            get {
                object obj = ResourceManager.GetObject("UploadToWeb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ValidationFunction {
            get {
                object obj = ResourceManager.GetObject("ValidationFunction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View {
            get {
                object obj = ResourceManager.GetObject("View", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
