//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tawala.Projects.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tawala.Projects.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backup.
        /// </summary>
        public static string BackupFileExtension {
            get {
                return ResourceManager.GetString("BackupFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string DocumentComponentVisibleTypeName {
            get {
                return ResourceManager.GetString("DocumentComponentVisibleTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string DocumentDefaultBaseName {
            get {
                return ResourceManager.GetString("DocumentDefaultBaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\uc1\deff0
        ///{\fonttbl
        ///{\f0\fswiss Arial;}
        ///}
        ///\fs20{\colortbl;
        ///\red0\green0\blue0;
        ///\red255\green255\blue255;
        ///}
        ///\pard \tx2880{\f0\fs20\cf1 ~@!~[Replace this with your question. Underscores create blanks.]~@!~ ____________________}\par }.
        /// </summary>
        public static string FibItemDefaultRTF {
            get {
                return ResourceManager.GetString("FibItemDefaultRTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @^~[Replace this with your question. Underscores create blanks.]~^@ __________.
        /// </summary>
        public static string FibItemDefaultText {
            get {
                return ResourceManager.GetString("FibItemDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string FormComponentVisibleTypeName {
            get {
                return ResourceManager.GetString("FormComponentVisibleTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string FormDefaultBaseName {
            get {
                return ResourceManager.GetString("FormDefaultBaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  from .
        /// </summary>
        public static string GetStatementFrom {
            get {
                return ResourceManager.GetString("GetStatementFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;No Forms Selected&quot;.
        /// </summary>
        public static string GetStatementNoFormsSelected {
            get {
                return ResourceManager.GetString("GetStatementNoFormsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  where .
        /// </summary>
        public static string GetStatementWhere {
            get {
                return ResourceManager.GetString("GetStatementWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\uc1\deff0
        ///{\fonttbl
        ///{\f0\fswiss Arial;}
        ///}
        ///\fs36{\colortbl;
        ///\red0\green0\blue0;
        ///\red255\green255\blue255;
        ///}
        ///\pard \tx2880{\f0\fs36\cf1 [Replace this with heading of your own.]}\par }.
        /// </summary>
        public static string HeadingItemDefaultRTF {
            get {
                return ResourceManager.GetString("HeadingItemDefaultRTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\uc1\deff0
        ///{\fonttbl
        ///{\f0\fswiss Arial;}
        ///}
        ///{\colortbl;
        ///\red0\green0\blue0;
        ///\red255\green255\blue255;
        ///}
        ///\pard\tx2880\f0\fs20\cf1 ~@!~[Replace this with your question. Use Enter key to add choices below.]~@!~\par    a) \par }.
        /// </summary>
        public static string MCItemDefaultRTF {
            get {
                return ResourceManager.GetString("MCItemDefaultRTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~@!~[Replace this with your question. Use Enter key to add choices below.]~@!~.
        /// </summary>
        public static string MCItemDefaultText {
            get {
                return ResourceManager.GetString("MCItemDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of $NAME.
        /// </summary>
        public static string PasteName1 {
            get {
                return ResourceManager.GetString("PasteName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy ($NUM) of $NAME.
        /// </summary>
        public static string PasteName2 {
            get {
                return ResourceManager.GetString("PasteName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _InviteeID.
        /// </summary>
        public static string PrivateInvitationVariableLabel {
            get {
                return ResourceManager.GetString("PrivateInvitationVariableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string ProcessComponentVisibleTypeName {
            get {
                return ResourceManager.GetString("ProcessComponentVisibleTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string ProcessDefaultBaseName {
            get {
                return ResourceManager.GetString("ProcessDefaultBaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string ProjectDefaultName {
            get {
                return ResourceManager.GetString("ProjectDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skips to {0}.
        /// </summary>
        public static string SkipSummaryAlwaysSkip {
            get {
                return ResourceManager.GetString("SkipSummaryAlwaysSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No instructions.  Click edit link on left to add instructions..
        /// </summary>
        public static string SkipSummaryEmpty {
            get {
                return ResourceManager.GetString("SkipSummaryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May skip to: {0}.
        /// </summary>
        public static string SkipSummaryMaySkip {
            get {
                return ResourceManager.GetString("SkipSummaryMaySkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SkipTo commands in instructions..
        /// </summary>
        public static string SkipSummaryNoSkips {
            get {
                return ResourceManager.GetString("SkipSummaryNoSkips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\uc1\deff0
        ///{\fonttbl
        ///{\f0\fswiss Arial;}
        ///{\f1\fnil Default Font;}
        ///}
        ///\fs20{\colortbl;
        ///\red0\green0\blue0;
        ///\red255\green255\blue255;
        ///\red0\green0\blue1;
        ///}\pard \tx2880{\f1\fs21\cf3 [Replace this with text of your own.]}\par }.
        /// </summary>
        public static string TextItemDefaultRTF {
            get {
                return ResourceManager.GetString("TextItemDefaultRTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string UntitledString {
            get {
                return ResourceManager.GetString("UntitledString", resourceCulture);
            }
        }
    }
}
