// Copyright © 2005-2009 Tawala Systems, Inc. All rights reserved.
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using Tawala.Common;
using Tawala.Projects.Components;
using Tawala.Projects.Documents;
using Tawala.Projects.Fields;
using Tawala.Projects.Forms;
using Tawala.Projects.Images;
using Tawala.Projects.Processes;
using Tawala.Projects.Properties;
using Tawala.XmlSupport;
using Process=Tawala.Projects.Processes.Process;

namespace Tawala.Projects
{
    /// <summary>
    /// Static methods for Creating, Loading and saving the Current Project
    /// As well as methods for a Project object.
    /// </summary>
    public class Project
    {
        #region ProjectFileOpenResult enum

        public enum ProjectFileOpenResult
        {
            OK,
            InvalidFile,
            NewerXmlFormat
        } ;

        #endregion

        private const string xmlDeclaration = "<?xml version=\"1.0\" encoding=\"utf-8\" ?>\r\n";
        public const string XmlFormatVersion = "1.16";

        private const string xmlProjectEndTag = "</project>\r\n";

        private const string xmlProjectStartTag =
            "<project name=\"{0}\" themePath=\"{1}\" format=\"" + XmlFormatVersion + "\" designerBuild=\"{2}\">\r\n";

        private const string xmlRequestEndTag = "</request>\r\n";
        private const string xmlRequestStartTag = "<request type=\"uploadProject\" protocol=\"1.0\">\r\n";
        private static readonly ModifiedState modifiedState;
        private static Project current;

        private static ProjectFieldMapById fieldMapById = new ProjectFieldMapById();
        private static ProjectFieldMapByName fieldMapByName = new ProjectFieldMapByName();

        private static ProjectFunctionMapById functionMapById = new ProjectFunctionMapById();
        private static GraphicImageList images = new GraphicImageList();

        private static ProjectInvitationMapById invitationMapById = new ProjectInvitationMapById();
        private static IImageDefinitionCollection newImages = new ImageDefinitionCollection();
        private static int nextUniqueID = 1;
        private static ProjectEvents projectEvents = new ProjectEvents();
        private readonly Variable privateInvitationInviteeID = new Variable(Resources.PrivateInvitationVariableLabel, true);

        /// <summary>
        /// a conglomerate list that contains both "real" document components
        /// and virtual document generated by Processes
        /// </summary>
        private readonly DocumentList realOrVirtualDocumentList = new DocumentList();

        /// <summary>
        /// list of documents created "on the fly" in Processes
        /// </summary>
        /// <remarks>
        /// this is a private list that gets updated only via GetRealOrVirtualDocument()
        /// </remarks>
        private readonly DocumentList virtualDocumentList = new DocumentList();

        private FormList allForms;
        private IProjectComponent currentComponent;
        private DocumentList documentList = new DocumentList();
        private FormList formList = new FormList();
        private string globalFibItemStyle;
        private string globalMCItemStyle;
        private string globalTextItemStyle;
        private int nextDocument = 1;
        private int nextForm = 1;
        private int nextProcess = 1;
        private PageHeader pageHeader = new PageHeader();
        private ProcessList processList = new ProcessList();
        private string projectName = "";
        private string themePath = "default";

        /// <summary>
        /// static class constructor
        /// </summary>
        static Project()
        {
            modifiedState = new ModifiedState();
        }

        /// <summary>
        /// Private Project constructor.  Use static methods.
        /// </summary>
        private Project()
        {
            current = this;

            projectName = Resources.ProjectDefaultName;

            // enable add/remove events on these collections

            formList.EnableEvents = true;
            documentList.EnableEvents = true;
            processList.EnableEvents = true;

            // a new project is empty so have old and new hashes the same as we don't need to save the new
            // empty project -- we only care if the user modifies it.

            modifiedState.Reset();
        }

        public static ProjectFieldMapById FieldMapById { get { return fieldMapById; } }

        public static ProjectFieldMapByName FieldMapByName { get { return fieldMapByName; } }

        public static ProjectFunctionMapById FunctionMapById { get { return functionMapById; } }

        public static ProjectInvitationMapById InvitationMapById { get { return invitationMapById; } }

        // DO NOT create new object here -- gets weird as we have a static constructor
        // and this is a static initializer that creates an instance.  Ordering can be unpredictable

        public static Project Current { get { return current; } }

        /// <summary>
        /// Project class access to ProjectEvents class.
        /// </summary>
        public static ProjectEvents Events { get { return projectEvents; } }

		// kludge to reduce load time of large projects
		// jdf - 5/13/10
		public static bool LoadingProjectXml { get; set; }

    	/// <summary>
        /// Returns true if the project has been modified, false otherwise.
        /// Used to determined if a message box needs to be displayed when exiting.
        /// </summary>
        public bool Modified { get { return modifiedState.Test(); } }

        public static int NextUniqueID { get { return nextUniqueID++; } }

        public PageHeader PageHeader { get { return pageHeader; } }

        /// <summary>
        /// Return a readonly IList wrapper around the formList.
        /// This allows the ProjectPane to repopulate itself on a OpenProject event.
        /// </summary>
        public ReadOnlyCollection<IForm> FormList { get { return formList.AsReadOnly(); } }

        /// <summary>
        /// Return a list of forms marked as Starting Points
        /// </summary>
        public FormList StartingPointList
        {
            get
            {
                var startingPointList = new FormList();

                foreach (IForm form in formList)
                {
                    if (form.StartingPoint)
                    {
                        startingPointList.Add(form);
                    }
                }

                return startingPointList;
            }
        }

        public FormList AllForms
        {
            get
            {
                if (allForms == null)
                {
                    allForms = createCombinedFormList();
                }
                else if (allForms.Count == 0)
                {
                    allForms = createCombinedFormList();
                }

                return allForms;
            }
        }

        public string ThemePath
        {
            get { return themePath; }
            set
            {
                bool changed = themePath.CompareTo(value) != 0;
                themePath = value;

                if (changed)
                {
                    Events.RaiseThemeChangedEvent();
                }
            }
        }

        public IProjectComponent CurrentComponent { get { return currentComponent; } }

        public string GlobalFibItemStyle { get { return globalFibItemStyle; } set { globalFibItemStyle = value; } }

        public string GlobalMCItemStyle { get { return globalMCItemStyle; } set { globalMCItemStyle = value; } }

        public int GlobalMCItemColumnCount { get; set; }

        public string GlobalTextItemStyle { get { return globalTextItemStyle; } set { globalTextItemStyle = value; } }

        public string Name { get { return projectName; } set { projectName = value; } }

        /// <summary>
        /// Return a readonly IList wrapper around the documentList.
        /// This allows it to be used as a DataSource for document name since the Document.ToString() method
        /// has been overriden to return a document name.
        /// </summary>
        public ReadOnlyCollection<IDocument> DocumentList { get { return documentList.AsReadOnly(); } }

        /// <summary>
        /// Return a readonly IList reference to realOrVirtualDocumentList
        /// </summary>
        public IList<IDocument> RealOrVirtualDocumentList { get { return realOrVirtualDocumentList.AsReadOnly(); } }

        public static GraphicImageList Images { get { return images; } }

        public static IImageDefinitionCollection NewImages { get { return newImages; } }

        /// <summary>
        /// Return a readonly IList wrapper around the processList.
        /// </summary>
        public ReadOnlyCollection<Process> ProcessList { get { return processList.AsReadOnly(); } }

		//public VariableList AllVariables
		//{
		//    get
		//    {
		//        var allVariables = new VariableList();

		//        foreach (Process proc in ProcessList)
		//        {
		//            foreach (Variable var in proc.Variables)
		//            {
		//                allVariables.AddUnique(var);
		//            }
		//        }

		//        foreach (IForm form in FormList)
		//        {
		//            foreach (IFormItem item in form.ItemList)
		//            {
		//                if (item is SkipInstructionsItem)
		//                {
		//                    foreach (Variable var in ((SkipInstructionsItem)item).Instructions.Variables)
		//                    {
		//                        allVariables.AddUnique(var);
		//                    }
		//                }
		//            }
		//        }

		//        allVariables.AddUnique(privateInvitationInviteeID);

		//        return allVariables;
		//    }
		//}
    	private VariableList allVariables;
		public VariableList AllVariables
		{
			get
			{
				if (allVariables == null)
				{
					allVariables = new VariableList();
				}

				// kludge to reduce load time of large projects
				// jdf - 5/13/10
				if (LoadingProjectXml && allVariables.Count > 0)
				{
					return allVariables;
				}

				allVariables.Clear();
				foreach (Process proc in ProcessList)
				{
					foreach (Variable var in proc.Variables)
					{
						allVariables.AddUnique(var);
					}
				}

				foreach (IForm form in FormList)
				{
					foreach (IFormItem item in form.ItemList)
					{
						if (item is SkipInstructionsItem)
						{
							foreach (Variable var in ((SkipInstructionsItem)item).Instructions.Variables)
							{
								allVariables.AddUnique(var);
							}
						}
					}
				}

				allVariables.AddUnique(privateInvitationInviteeID);

				return allVariables;
			}
		}

        /// <summary>
        /// Create a new Project
        /// </summary>
        public static void New()
        {
            Log.LogInfo("");

            resetStaticMembers();

            new Project();

            raiseNewProjectEvents();
        }

        /// <summary>
        /// Create a new Project
        /// </summary>
        public static void New(IXmlElement element)
        {
            Log.LogInfo("(IXmlElement)");

            resetStaticMembers();

            new Project();

            Current.Name = element.GetAttribute("name");
            Debug.Assert(Current.Name != null);

            Current.pageHeader = new PageHeader(element);

            setFormItemStyles(element);

            string themePath = element.GetAttribute("themePath");

            if (!string.IsNullOrEmpty(themePath))
            {
                Current.ThemePath = themePath;
            }

            images = new GraphicImageList(element.GetChild("images"));

            raiseNewProjectEvents();
        }

        public static void Create(IXmlElement element)
        {
            resetStaticMembers();

            new Project();

            Current.Name = element.GetAttribute("name");
            Current.ThemePath = element.GetAttribute("themePath");

            newImages = new ImageDefinitionCollection(element.GetChild("images"));

            Current.SetFormList(new FormList(element.GetChild("forms")));

            foreach (IForm form in Current.FormList)
            {
                form.ItemList.ResolveFunctionReferences();
            }

            Current.SetDocumentList(new DocumentList(element.GetChild("documents")));
            Current.updateRealOrVirtualDocumentList();

            Current.SetProcessList(new ProcessList(element.GetChild("processes")));

            foreach (IForm form in Current.FormList)
            {
                form.ResolveProcessReferences();
                form.ItemList.ResolveFieldReferences();
            }

            foreach (IForm form in Current.FormList)
            {
                form.ItemList.ResolveFieldReferences();
            }

            Current.EnableComponentEvents(true);

            Current.ResetModifiedState();
        }

        private static void setFormItemStyles(IXmlElement element)
        {
            if (element.HasChild("styles"))
            {
                Current.globalFibItemStyle = element.GetChild("styles").GetAttribute("fibItemStyle");
                Current.globalMCItemStyle = element.GetChild("styles").GetAttribute("mcItemStyle");
                Current.globalTextItemStyle = element.GetChild("styles").GetAttribute("textItemStyle");
            }
        }

        private static void resetStaticMembers()
        {
            nextUniqueID += 1000;

            fieldMapById = new ProjectFieldMapById();
            fieldMapByName = new ProjectFieldMapByName();
            functionMapById = new ProjectFunctionMapById();
            invitationMapById = new ProjectInvitationMapById();
            images = new GraphicImageList();
            newImages = new ImageDefinitionCollection();
        }

        private static void raiseNewProjectEvents()
        {
            projectEvents.RaiseNewProjectEvent(new ProjectEventArgs(current.projectName));
            projectEvents.RaiseCurrentComponentSetEvent(new ComponentEventArgs(null));
        }

        /// <summary>
        /// FOR TESTING PURPOSES ONLY! Creates a "clean" Project. 
        /// </summary>
        public static void NewTestProject()
        {
            resetStaticMembers();

            new Project();

            projectEvents = new ProjectEvents();
        }

        public static ProjectFileOpenResult Open(string filePath)
        {
            long startTicks = Log.LogEnter("path = '{0}'", filePath);

            ProjectFileOpenResult result = ProjectFileOpenResult.InvalidFile;

            try
            {
                using (Stream stream = File.OpenRead(filePath))
                {
                    result = open(stream);
                }
            }
            catch (Exception e)
            {
                Log.LogException(e);
                throw;
            }

            Log.LogExit(startTicks);

            return result;
        }

        private static ProjectFileOpenResult open(Stream stream)
        {
            Events.RaiseOpeningProjectEvent();

            // slop accounts for possible binary bytes proceeding XML in prior versions which weren't pure XML.
            const int slop = 8;
            byte[] signature1 = Encoding.UTF8.GetBytes("<?xml version=\"1.0\" encoding=\"utf-8\"");
            byte[] signature2 = Encoding.UTF8.GetBytes("<?xml version=\"1.0\" encoding=\"UTF-8\"");
            var byteArray = new byte[signature1.Length + slop];

            // don't even bother in this case
            if (stream.Length < byteArray.Length)
            {
                return ProjectFileOpenResult.InvalidFile;
            }

            stream.Position = 0;
            stream.Read(byteArray, 0, byteArray.Length);
            stream.Position = 0;

            int matched = 0;
            int offset;

            for (offset = 0; offset < slop; ++offset)
            {
                for (matched = 0; matched < signature1.Length; ++matched)
                {
                    if (signature1[matched] != byteArray[matched + offset] && signature2[matched] != byteArray[matched + offset])
                    {
                        break;
                    }
                }

                if (matched == signature1.Length)
                {
                    break;
                }
            }

            if (matched != signature1.Length)
            {
                return ProjectFileOpenResult.InvalidFile;
            }

            if (offset == 0) // pure XML format (newer)
            {
                var converter = new TawalaProjectConverter(stream);
                if (!converter.ConvertXmlToProject())
                {
                    return ProjectFileOpenResult.NewerXmlFormat;
                }

                modifiedState.Reset();
            }
            else
            {
                string xmlString = new BinaryReader(stream, Encoding.UTF8).ReadString();

                using (var memoryStream = new MemoryStream())
                {
                    // make XML string into byte array
                    byte[] xmlByteArray = Encoding.UTF8.GetBytes(xmlString);

                    // write XML to memory stream
                    memoryStream.Write(xmlByteArray, 0, xmlByteArray.Length);

                    var converter = new TawalaProjectConverter(memoryStream);
                    converter.ConvertXmlToProject();

                    // Force modification state to always be true because of open from XML
                    modifiedState.ForceTrue();
                }
            }

            Events.RaiseProjectOpenedEvent(new ProjectEventArgs(current.projectName));

            // raise "current component set" as initially set to none/null
            projectEvents.RaiseCurrentComponentSetEvent(new ComponentEventArgs(null));

            return ProjectFileOpenResult.OK;
        }

        /// <summary>
        /// When saving to a file, use this method.
        /// </summary>
        public static void Save(string path)
        {
            long startTicks = Log.LogEnter("path = '{0}'", path);

            try
            {
                string oldName = Current.Name;
                string newName = Path.GetFileNameWithoutExtension(path);

                Current.Name = newName;

                using (Stream stream = File.Create(path))
                {
                    save(stream);
                }

                var args = new SaveProjectEventArgs(oldName, newName);

                projectEvents.RaiseSaveProjectEvent(args);

                modifiedState.Reset();
            }
            catch (Exception e)
            {
                Log.LogException(e);
                throw;
            }

            Log.LogExit(startTicks);
        }

        public static void SaveWithDebugInfo(string path, string debugInfo)
        {
            Save(path);

            using (Stream stream = File.OpenWrite(path))
            {
                stream.Seek(0, SeekOrigin.End);
                byte[] byteArray = Encoding.UTF8.GetBytes("\r\nDEBUG INFO:\r\n" + debugInfo);
                stream.Write(byteArray, 0, byteArray.Length);
            }
        }

        /// <summary>
        /// All Save operations should ultimately funnel through this function.
        /// If not, the data may not be synchronized with the UI!
        /// </summary>
        private static void save(Stream stream)
        {
            try
            {
                if (current != null)
                {
                    byte[] byteArray = Encoding.UTF8.GetBytes(current.ToXmlForSaving());
                    stream.Write(byteArray, 0, byteArray.Length);
                }
            }
            catch (Exception e)
            {
                Log.LogException(e);
                throw;
            }
        }

        public void ResetModifiedState()
        {
            modifiedState.Reset();
        }

        // REVISIT: Remove this after Project conversion from XML is in place.
        public void SetFormList(FormList forms)
        {
            formList = forms;
            allForms = null;
        }

        public void SetProcessList(ProcessList processes)
        {
            processList = processes;
        }

        public void SetDocumentList(DocumentList documents)
        {
            documentList = documents;
        }

        private FormList createCombinedFormList()
        {
            var combinedForms = new FormList();
            var localDataSourceNames = new Collection<string>();

            foreach (IForm form in FormList)
            {
                combinedForms.Add(form);
                if (form.IsDataSource)
                {
                    localDataSourceNames.Add(form.DataSourceName);
                }
            }

            foreach (IForm externalForm in FieldProviders.ExternalForms)
            {
                if (!localDataSourceNames.Contains(externalForm.Name))
                {
                    combinedForms.Add(externalForm);
                }
            }

            return combinedForms;
        }

        public void MoveComponent(IProjectComponent component, int index)
        {
            if (component is IForm)
            {
                formList.EnableEvents = false;
                formList.Remove(component as IForm);
                formList.Insert(index, component as IForm);
                formList.EnableEvents = true;
            }
            if (component is IProcess)
            {
                processList.EnableEvents = false;
                processList.Remove(component as Process);
                processList.Insert(index, component as Process);
                processList.EnableEvents = true;
            }
            if (component is IDocument)
            {
                documentList.EnableEvents = false;
                documentList.Remove(component as IDocument);
                documentList.Insert(index, component as IDocument);
                documentList.EnableEvents = true;
            }

            allForms = null;
        }

        /// <summary>
        /// Enables or disables raising of Component events
        /// </summary>
        public void EnableComponentEvents(bool enable)
        {
            formList.EnableEvents = enable;
            documentList.EnableEvents = enable;
            processList.EnableEvents = enable;
        }

        /// <summary>
        /// Create new form and add to end of form list.
        /// </summary>
        public IForm AddForm()
        {
            // create new form with unique name
            string name;
            do
            {
                // create a name consisting of the base name plus the Form ID
                int formNum = nextForm++;
                name = Resources.FormDefaultBaseName + " " + formNum;
            } while (formList.IndexOf(name) >= 0); // making sure it doesn't already exist

            IForm form = ComponentMaker.MakeFormObject(name);

            // if only form in project, make it a starting point
            if (formList.Count == 0)
            {
                form.StartingPoint = true;
            }

            allForms = null;

            // add form to list
            formList.Add(form);

            return form;
        }

        /// <summary>
        /// Get a Form object by name.
        /// </summary>
        public IForm GetForm(string name)
        {
            return formList[name];
        }

        public IForm GetFormContaining(IFormItem item)
        {
            foreach (IForm form in AllForms)
            {
                if (form.ItemList.Contains(item))
                {
                    return form;
                }
            }

            return Form.NULL;
        }

        /// <summary>
        /// Paste a Form object into the Project.
        /// The object shouldn't already be in the list.
        /// </summary>
        public bool PasteForm(IForm form)
        {
            return formList.Paste(form);
        }

        /// <summary>
        /// Rename form in list.
        /// </summary>
        public bool RenameForm(string oldName, string newName)
        {
            return formList.Rename(oldName, newName);
        }

        public void SetCurrentComponent(IProjectComponent component)
        {
            if (currentComponent != component)
            {
                IProjectComponent newComp = null;

                if (formList.ContainsComponent(component))
                {
                    newComp = component;
                }
                else if (processList.ContainsComponent(component))
                {
                    newComp = component;
                }
                else if (documentList.ContainsComponent(component))
                {
                    newComp = component;
                }

                currentComponent = newComp;

                Events.RaiseCurrentComponentSetEvent(new ComponentEventArgs(currentComponent));
            }
        }

        /// <summary>
        /// Remove form from list.
        /// </summary>
        public void RemoveForm(string formName)
        {
            IForm form = formList[formName];

            if (form != null)
            {
                allForms = null;
                formList.Remove(form);
            }
        }

        public string ToXmlForSaving()
        {
            var xmlString = new StringBuilder();

            xmlString.Append(xmlDeclaration);

            xmlString.Append(toLeanXml());

            return xmlString.ToString();
        }

        /// <summary>
        /// Sets the styles of all FIBs in all forms in the project to the specified style.
        /// </summary>
        public void SetAllFibStyles(string style)
        {
            GlobalFibItemStyle = style;

            foreach (IForm form in AllForms)
            {
                foreach (IFormItem formItem in form.ItemList)
                {
                    var fibItem = formItem as IFibItem;

                    if (fibItem != null)
                    {
                        fibItem.Style = style;
                    }
                }
            }

            refreshFormPreview();
        }

        /// <summary>
        /// Sets the styles of all MCQs in all forms in the project to the specified style.
        /// </summary>
        public void SetAllMCQStyles(string style, bool paddingBottom)
        {
            GlobalMCItemStyle = style;

            foreach (IMcqItem mcItem in getAllMCItems())
            {
                mcItem.Style = style;
                mcItem.ColumnCount = 0;
                mcItem.PaddingBottom = paddingBottom;
            }

            refreshFormPreview();
        }

        /// <summary>
        /// Sets the styles of all MCQs in all forms in the project to the specified style and column count.
        /// </summary>
        public void SetAllMCQStyles(string style, int columnCount, bool paddingBottom)
        {
            GlobalMCItemStyle = style;
            GlobalMCItemColumnCount = columnCount;

            foreach (IMcqItem mcItem in getAllMCItems())
            {
                mcItem.Style = style;
                mcItem.ColumnCount = columnCount;
                mcItem.PaddingBottom = paddingBottom;
            }

            refreshFormPreview();
        }

        private Collection<IMcqItem> getAllMCItems()
        {
            var mcItems = new Collection<IMcqItem>();

            foreach (IForm form in AllForms)
            {
                foreach (IFormItem formItem in form.ItemList)
                {
                    var mcItem = formItem as IMcqItem;

                    if (mcItem != null)
                    {
                        mcItems.Add(mcItem);
                    }
                }
            }

            return mcItems;
        }

        /// <summary>
        /// Sets the styles of all text Items in all forms in the project to the specified style.
        /// </summary>
        public void SetAllTextItemStyles(string style, bool paddingBottom)
        {
            GlobalTextItemStyle = style;

            foreach (IForm form in AllForms)
            {
                foreach (IFormItem formItem in form.ItemList)
                {
                    var textItem = formItem as ITextItem;

                    if (textItem != null)
                    {
                        textItem.Style = style;
                        textItem.PaddingBottom = paddingBottom;
                    }
                }
            }

            refreshFormPreview();
        }

        private static void refreshFormPreview()
        {
            Events.RaiseThemeChangedEvent();
        }

        /// <summary>
        /// Returns an XML string representing the Project and all of its
        /// form data, if any.
        /// </summary>
        public string ToXmlForUpload(string credentialsXml)
        {
            var xmlString = new StringBuilder();

            xmlString.Append(xmlDeclaration);
            xmlString.Append(xmlRequestStartTag);

            xmlString.Append(credentialsXml);

            xmlString.Append(toLeanXml());

            xmlString.Append(xmlRequestEndTag);

            return xmlString.ToString();
        }

        public string ToXml()
        {
            return toLeanXml();
        }

        /// <summary>
        /// Returns an XML string representing the Project and all of its
        /// form data, if any.
        /// </summary>
        private string toXml()
        {
            var xmlString = new StringBuilder();

            xmlString.AppendFormat(xmlProjectStartTag, XMLStringFormatter.EscapeAttributeText(projectName),
                                   XMLStringFormatter.EscapeAttributeText(themePath), Config.Build);

            xmlString.Append(pageHeader.ToXml());

            xmlString.Append(stylesXml());

            xmlString.Append(formList.ToXml());

            xmlString.Append(processList.ToXml());
            xmlString.Append(documentList.ToXml());

            xmlString.Append(images.ToXml());
            xmlString.Append(newImages.ToXml());

            xmlString.Append(xmlProjectEndTag);

            return xmlString.ToString();
        }

        private string stylesXml()
        {
            var xmlString = new StringBuilder();

            if (globalFibItemStyle != null || globalMCItemStyle != null || globalTextItemStyle != null)
            {
                xmlString.Append(@"<styles");

                if (globalFibItemStyle != null)
                {
                    xmlString.AppendFormat(@" fibItemStyle=""{0}""", globalFibItemStyle);
                }

                if (globalMCItemStyle != null)
                {
                    xmlString.AppendFormat(@" mcItemStyle=""{0}""", globalMCItemStyle);
                }

                if (globalTextItemStyle != null)
                {
                    xmlString.AppendFormat(@" textItemStyle=""{0}""", globalTextItemStyle);
                }

                xmlString.Append(@" />");
            }

            return xmlString.ToString();
        }

        /// <summary>
        /// Returns an XML string representing the Project after unused objects are removed.
        /// </summary>
        private string toLeanXml()
        {
            projectEvents.RaiseSynchronizeProjectEvent();

            removeUnusedImages();
            return toXml();
        }

        private void removeUnusedImages()
        {
            string projectXmlString = toXml();

            IXmlElement element = new XmlElement(projectXmlString);

            var usedImageIds = new Collection<string>();

            foreach (IXmlElement imageElement in element.GetDescendants("image"))
            {
                usedImageIds.Add(imageElement.GetAttribute("id"));
            }

            var unusedImageIds = new Collection<string>();

            foreach (GraphicImage image in images)
            {
                if (!usedImageIds.Contains(image.Id))
                {
                    unusedImageIds.Add(image.Id);
                }
            }

            foreach (string imageId in unusedImageIds)
            {
                images.Remove(images[imageId]);
            }
        }

        /// <summary>
        /// Create new document and add to end of document list.
        /// </summary>
        public IDocument AddDocument()
        {
            // create new document with unique name
            string name;
            do
            {
                // create a name consisting of the base name plus the Process ID
                int docID = nextDocument++;
                name = Resources.DocumentDefaultBaseName + " " + docID;
            } while (documentList.IndexOf(name) >= 0); // making sure it doesn't already exist

            IDocument doc = ComponentMaker.MakeDocumentObject(name);

            // add document to list
            documentList.Add(doc);

            // update our conglomerate list of real and virtual documents
            updateRealOrVirtualDocumentList();

            return doc;
        }

        public void AddDocument(IDocument doc)
        {
            documentList.Add(doc);
            updateRealOrVirtualDocumentList();
        }

        /// <summary>
        /// Get a Document object by name.
        /// </summary>
        public IDocument GetDocument(string documentName)
        {
            return (documentList[documentName] ?? Document.NULL);
        }

        /// <summary>
        /// Paste a Document object into the Project.
        /// The object shouldn't already be in the list.
        /// </summary>
        public bool PasteDocument(IDocument doc)
        {
            bool result = documentList.Paste(doc);
            if (result)
            {
                updateRealOrVirtualDocumentList();
            }
            return result;
        }

        /// <summary>
        /// Remove document from list.
        /// </summary>
        public void RemoveDocument(string name)
        {
            // remove document from list
            IDocument doc = documentList[name];
            if (doc != null)
            {
                documentList.Remove(doc);

                // update our conglomerate list of real and virtual documents
                updateRealOrVirtualDocumentList();
            }
        }

        /// <summary>
        /// Remove document from list.
        /// </summary>
        public void RemoveDocument(IDocument doc)
        {
            // remove document from list
            documentList.Remove(doc);

            // update our conglomerate list of real and virtual documents
            updateRealOrVirtualDocumentList();
        }

        /// <summary>
        /// Rename document in list.
        /// </summary>
        public bool RenameDocument(string oldName, string newName)
        {
            bool result = documentList.Rename(oldName, newName);
            if (result)
            {
                updateRealOrVirtualDocumentList();
            }
            return result;
        }

        /// <summary>
        /// fetch a document by name, looking in both the documentList ("real" Documents)
        /// and the virtualDocumentList
        /// </summary>
        /// <param name="name">
        /// document name to search for
        /// </param>
        /// <param name="createNew">
        /// if true, and if a document of the passed name does not already exist,
        /// one is created and added to the virtualDocumentList
        /// </param>
        public IDocument GetRealOrVirtualDocument(string name, bool createNew)
        {
            // see if the named document is in the "real" Document component list
            IDocument doc = documentList[name] ?? virtualDocumentList[name];

            // if not found, and if the flag is set to create a virtual document
            if (doc == null && createNew)
            {
                // create it and add it to the virtual doc list
                doc = ComponentMaker.MakeDocumentObject(name);
                virtualDocumentList.Add(doc);

                // update our conglomerate list of real and virtual documents
                updateRealOrVirtualDocumentList();
            }

            return doc;
        }

        /// <summary>
        /// updates the conglomerate list when a change is made to either of the others
        /// </summary>
        private void updateRealOrVirtualDocumentList()
        {
            Debug.Assert(realOrVirtualDocumentList != null);

            // clear the list
            realOrVirtualDocumentList.Clear();

            // add the documents from the real and virtual doc lists
            foreach (IDocument doc in documentList)
            {
                realOrVirtualDocumentList.Add(doc);
            }
            foreach (IDocument doc in virtualDocumentList)
            {
                realOrVirtualDocumentList.Add(doc);
            }

            Events.RaiseDocumentChangedEvent(new ComponentEventArgs(Document.NULL));
        }

        // list of images

        /// <summary>
        /// Create new process and add to end of process list.
        /// </summary>
        public Process AddProcess()
        {
            // create new process with unique name
            string name;
            do
            {
                // create a name consisting of the base name plus the Process ID
                int procID = nextProcess++;
                name = Resources.ProcessDefaultBaseName + " " + procID;
            } while (processList.IndexOf(name) >= 0); // making sure it doesn't already exist

            var process = new Process(name);

            // add process to list
            processList.Add(process);

            return (process);
        }

        /// <summary>
        /// Adds the specified process to the process list.
        /// </summary>
        public Process AddProcess(Process process)
        {
            if (processList.IndexOf(process.Name) == -1)
            {
                processList.Add(process);
            }

            return (process);
        }

        /// <summary>
        /// Get a Process object by name.
        /// </summary>
        public Process GetProcess(string name)
        {
            return (processList[name] ?? Process.NULL);
        }

        /// <summary>
        /// Get a Process object by statement.
        /// </summary>
        public Process GetProcessOrSkipInstructions(ProcessStatement statement)
        {
            // look for the statement in the Process list
            Process process = processList[statement];

            // not there?
            if (process == null)
            {
                // check the Skip Instructions in the Forms
                foreach (IForm form in formList)
                {
                    if ((process = form.GetSkipInstructions(statement)) != null)
                    {
                        break;
                    }
                }
            }

            return process;
        }

        /// <summary>
        /// Paste a Process object into the Project.
        /// The object shouldn't already be in the list.
        /// </summary>
        public bool PasteProcess(Process process)
        {
            return processList.Paste(process);
        }

        /// <summary>
        /// Remove process from list.
        /// </summary>
        public void RemoveProcess(string name)
        {
            // remove process from list
            Process process = processList[name];
            if (process != null)
            {
                processList.Remove(process);

                // disconnect it from any forms it may have been associated with
                formList.DisconnectProcessFromAllForms(process);
            }
        }

        /// <summary>
        /// Rename process in list.
        /// </summary>
        public bool RenameProcess(string oldName, string newName)
        {
            return processList.Rename(oldName, newName);
        }

        /// <summary>
        /// Associates the passed Process name with the named Form
        /// </summary>
        /// <param name="process">The Process to connect</param>
        /// <param name="form">The name of the Form to which the Process will be connected</param>
        public void ConnectProcessToForm(IProcess process, string form)
        {
            formList.ConnectProcessToForm(process, form);
        }

        /// <summary>
        /// Disconnects the connected Process from the named Form
        /// </summary>
        /// <param name="form">The name of the Form from which to disconnect any attached Process</param>
        public void DisconnectProcessFromForm(string form)
        {
            formList.DisconnectProcessFromForm(form);
        }

        /// <summary>
        /// Associates the passed PreProcess with the named Form
        /// </summary>
        public void ConnectPreProcessToForm(Process process, string formName)
        {
            IForm form = GetForm(formName);

            if (form != null)
            {
                form.ConnectedPreProcess = process;
            }
        }

        public void DisconnectPreProcessFromForm(string formName)
        {
            IForm form = GetForm(formName);

            if (form != null)
            {
                form.ConnectedPreProcess = null;
            }
        }

        /// <summary>
        /// Returns a list of forms to which a process is connected
        /// </summary>
        /// <param name="process">The process in question</param>
        public FormList GetFormList(Process process)
        {
            var fList = new FormList();

            foreach (IForm f in formList)
            {
                if (f.ConnectedPostProcess == process)
                {
                    fList.Add(f);
                }
            }

            return fList;
        }

        public FormList GetFormList(string processName)
        {
            var fList = new FormList();

            foreach (IForm f in formList)
            {
                if (f.ConnectedPostProcess != null)
                {
                    if (f.ConnectedPostProcess.Name == processName)
                    {
                        fList.Add(f);
                    }
                }
            }

            return fList;
        }

        /// <summary>
        /// Gets the default label corresponding to the specified form item
        /// </summary>
        public string GetDefaultLabel(IFormItem formItem)
        {
            IForm form = GetFormContaining(formItem);

            return form.GetDefaultLabel(formItem);
        }

        /// <summary>
        /// Gets the form item corresponding to the specified form item id
        /// </summary>
        public IFormItem GetFormItem(int formItemId)
        {
            foreach (IForm f in formList)
            {
                IFormItem item = f.GetFormItem(formItemId);

                if (item != null)
                {
                    return item;
                }
            }

            return null;
        }

        /// <summary>
        /// Get the number of forms to which the specified Process
        /// is currently connected.
        /// </summary>
        public int GetFormConnectionCount(IProcess process)
        {
            int count = 0;

            if (process != null)
            {
                // for each form in project...
                foreach (IForm f in formList)
                {
                    // if process is connected to form...
                    if (f.ConnectedPostProcess == process)
                    {
                        // update connection count
                        count++;
                    }
                }
            }

            return count;
        }

        public bool ValidComponentName(string name)
        {
            // strip off leading and trailing whitespace because existing labels won't have them
            string testName = name.Trim();

            if (testName.Length == 0)
            {
                return false;
            }

            return ValidLabelFormat(testName);
        }

        /// <summary>
        /// Determines whether a name is valid for use in an Append statement
        /// </summary>
        public bool ValidDocumentNameForAppendStatement(string name)
        {
            return ValidComponentName(name);
        }

        /// <summary>
        /// checks to see if the format of a label is legal
        /// </summary>
        public bool ValidLabelFormat(string label)
        {
            bool validFormat = true;

            if (label.Length > 0)
            {
                // the following formats are illegal:
                //	 1) leading double underscores (these denote reserved internal labels)
                //	 2) labels that contain a colon (:)
                //	 3) positive or negative integer or floating point numbers
                //			e.g. "3", "37.5", "-90"
                //	 4) positive or negative floating point numbers of the form "n."
                //			e.g. "5.", "-5."
                //
                validFormat = /*1*/ !(label.StartsWith("__")) && /*2*/ !(label.Contains(":")) && /*3*/
                                    !(Regex.Match(label, @"^-?\d*\.?\d+$").Success) && /*4*/ !(Regex.Match(label, @"^-?\d+\.?$").Success);
            }

            return validFormat;
        }

        /// <summary>
        /// checks to see if the format of a label is legal for a Form Field or Variable
        /// </summary>
        public bool ValidFieldLabelFormat(string label)
        {
            if (ValidLabelFormat(label) && label.Length > 0)
            {
                // default Question or Text label formats (including lower case, to avoid confusion) are illegal
                //		e.g., "Q1", "T2", "q22", "t1"
                //
                return !(Regex.Match(label, @"^[QqTt]\d+$").Success);
            }

            return false;
        }

        #region Nested type: ModifiedState

        /// <summary>
        /// Encapsulates the managing the modification state of the Project
        /// </summary>
        private class ModifiedState
        {
            private static readonly SHA1Managed sha1Hasher = new SHA1Managed();
            private byte[] newHash;
            private byte[] oldHash;

            /// <summary>
            /// Reset to unmodified
            /// </summary>
            internal void Reset()
            {
                oldHash = newHash = hash();
            }

            /// <summary>
            /// Test and return the results
            /// </summary>
            internal bool Test()
            {
                // we only check the hashes to see if they have changed if they are currently equal
                if (hashEqual())
                {
                    newHash = hash();
                }

                return !hashEqual();
            }

            /// <summary>
            /// Force Test() to always return true (for instance after XML conversion)
            /// </summary>
            internal void ForceTrue()
            {
                oldHash = new byte[] {1};
                newHash = hash();
            }

            /// <summary>
            /// Compute is 160 bit hash for the binary stream -- used as a modification flag
            /// Hopefully its not too expensive
            /// </summary>
            private static byte[] hash()
            {
                using (var ms = new MemoryStream())
                {
                    save(ms);
                    ms.Position = 0;
                    return sha1Hasher.ComputeHash(ms);
                }
            }

            /// <summary>
            /// Seems 160bit hashs which are byte arrays must be compared manually.  ARG!
            /// </summary>
            private bool hashEqual()
            {
                if (oldHash.Length != newHash.Length)
                {
                    return false;
                }

                for (int i = 0; i < oldHash.Length; ++i)
                {
                    if (oldHash[i] != newHash[i])
                    {
                        return false;
                    }
                }

                return true;
            }

            // hashes used for determining modification state of project.
        }

        #endregion
    }
}