//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tawala.Functions.Runtime.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tawala.Functions.Runtime.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //
        ///// Copyright © 2005-${YEAR} Tawala Systems, Inc. All rights reserved.
        /////
        ///using System;
        ///using System.ComponentModel;
        ///using System.Reflection;
        ///using System.Resources;
        ///using System.Runtime.InteropServices;
        ///using System.Runtime.CompilerServices;
        ///
        ///using FC = Tawala.Functions.Runtime.Private.FunctionClassAttribute;
        ///
        ///[assembly: AssemblyCompany(&quot;Tawala Systems, Inc.&quot;)]
        ///[assembly: AssemblyProduct(&quot;Tawala Designer&quot;)]
        ///[assembly: AssemblyCopyright(&quot;© 2005-${YEAR} Tawala Systems, Inc. All rights reserve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ASSEMBLY_INFO_TEMPLATE {
            get {
                return ResourceManager.GetString("ASSEMBLY_INFO_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //
        ///// Copyright © 2005-${YEAR} Tawala Systems, Inc. All rights reserved.
        /////
        ///using System;
        ///using System.Collections;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.ComponentModel;
        ///using System.Data;
        ///using System.Diagnostics;
        ///using System.IO;
        ///using System.Reflection;
        ///using System.Resources;
        ///using System.Text;
        ///using System.Xml.XPath;
        ///using System.Runtime.InteropServices;
        ///using System.Runtime.CompilerServices;
        ///
        ///using Tawala.Projects;
        ///using Tawala.Projects [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CODE_PREAMBLE_TEMPLATE {
            get {
                return ResourceManager.GetString("CODE_PREAMBLE_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		[Description(&quot;${PNAME} Composite&quot;)]
        ///		public class __composite_${PNAME} : AutoComposite
        ///		{
        ///		    ${PROPERTIES}
        ///		    
        ///   		    protected override void NotifyChanged(string name)
        ///		    {
        ///				Debug.WriteLine(&quot;__composite_${PNAME}.NotifyChanged(&apos;&quot; + name + &quot;&apos;)&quot;);
        ///				
        ///			    if (CompositePropertyChanged != null)
        ///			    {
        ///			        CompositePropertyChanged(this, new PropertyChangedEventArgs(&quot;${PNAME}&quot;));
        ///			    }
        ///			    
        ///			    base.NotifyChanged(name);
        ///		    }
        ///		}
        ///		
        ///		[Description(&quot;${P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string COMPOSITE_PROPERTY_TEMPLATE {
            get {
                return ResourceManager.GetString("COMPOSITE_PROPERTY_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	public sealed class FunctionRepositoryImpl : FunctionRepository, IFunctionRepository
        ///	{
        ///        public IFunctionInfoCollection Functions { get { return functions; } }
        ///
        ///        public ICategoryInfoCollection Categories { get { return categories; } }
        ///
        ///        public XPathNavigator Xml { get { return navigator.Clone(); } }
        ///
        ///		public Assembly GeneratedAssembly { get { return Assembly.GetExecutingAssembly(); }	}
        ///		public string Signature	{ get { return &quot;${REPOSITORYSIGNATURE}&quot;; } }
        ///		public string Cre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FUNCTION_REPOSITORY_TEMPLATE {
            get {
                return ResourceManager.GetString("FUNCTION_REPOSITORY_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///	public sealed class ${CLASSNAMEV} : Function
        ///	{
        ///		${PROPERTIES}
        ///		
        ///		public static IFunction CreateInstance() { return new ${CLASSNAMEV}(); }
        ///		
        ///  		public static event PropertyChangedEventHandler CompositePropertyChanged;
        ///  		
        ///  		public override void BeginEdit()
        ///  		{
        ///  		    CompositePropertyChanged += forwardChange;
        ///  		}
        ///  		
        ///  		public override void EndEdit()
        ///  		{
        ///   		    CompositePropertyChanged -= forwardChange;
        ///  		}
        ///  		
        ///  		private void forwardChange(object sender, Property [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FUNCTION_TEMPLATE {
            get {
                return ResourceManager.GetString("FUNCTION_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		private ${TYPE} prop_${FNAME}${FASSIGN};
        ///
        ///        [ParameterMarker]
        ///        [ParameterProperty(&quot;${GID}&quot;, typeof(${TYPE}), typeof(${TYPE}))]
        ///		public ${TYPE} ${PNAME}
        ///		{
        ///			get	{ return prop_${FNAME};	}
        ///			set
        ///			{
        ///				if (prop_${FNAME} != value) { prop_${FNAME} = value; NotifyChanged(&quot;${PNAME}&quot;);	}
        ///			}
        ///		}.
        /// </summary>
        internal static string PARAMETER_PROPERTY_TEMPLATE {
            get {
                return ResourceManager.GetString("PARAMETER_PROPERTY_TEMPLATE", resourceCulture);
            }
        }
    }
}
