//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TawalaTest.TestSupport.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TawalaTest.TestSupport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;tr:component-repository xmlns:tr=&quot;http://www.tawala.com/component-repository&quot;
        ///						 signature=&quot;-880504078&quot;&gt;
        ///	&lt;tr:categories&gt;
        ///		&lt;tr:category name=&quot;All&quot;&gt;
        ///			&lt;tr:element-id&gt;simple-list&lt;/tr:element-id&gt;
        ///			&lt;tr:element-id&gt;itemization-table&lt;/tr:element-id&gt;
        ///			&lt;tr:element-id&gt;choice-tally-table&lt;/tr:element-id&gt;
        ///			&lt;tr:element-id&gt;popular-choice-correlation-table&lt;/tr:element-id&gt;
        ///			&lt;tr:element-id&gt;popular-choice-display&lt;/tr:element-id&gt;
        ///			&lt;tr:element-id&gt;sum&lt;/tr:element-id&gt;
        ///			&lt;tr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string display_component_repository {
            get {
                return ResourceManager.GetString("display_component_repository", resourceCulture);
            }
        }
    }
}
