/** Legacy DirtBowl Registration header blocks (T2–T4) for Java upload. */

const REGISTRATION_TEXT_XML = {
  T1: `<paragraph indent="0" align="left"><tabPositions><tabStop position="2880"/></tabPositions><font size="280" color="B30000"><b><i><field name="Message"/></i></b></font></paragraph>`,
  T2: `<paragraph indent="0" align="center"><font face="Arial" size="220" color="CC0000"><b><field name="League"/></b></font></paragraph><paragraph indent="0" align="center"><font face="Arial" size="220" color="CC0000"><b><field name="SeasonYr"/></b></font><font face="Arial" size="220" color="CC0000"><b> Summer Basketball League: Games Only</b></font></paragraph><paragraph indent="0" align="center"><font face="Arial" size="180" color="CC0000"><b>Boys and Girls</b></font></paragraph><paragraph indent="0" align="center"></paragraph><paragraph indent="0" align="center"><font face="Arial" size="160" color="000000"><b>YOU ARE INVITED to participate in the Annual "</b></font><font face="Arial" size="160" color="000000"><b><field name="League"/></b></font><font face="Arial" size="160" color="000000"><b>" Basketball League and Tournament!</b></font></paragraph><paragraph indent="0" align="center"><font face="Arial" size="160" color="000000"><b>Information below.  If you are age 8-13, please join us!</b></font></paragraph>`,
  T3: `<paragraph indent="0" align="center"><tabPositions><tabStop position="2880"/></tabPositions><font face="Arial" size="200">Athletic Director: </font><font face="Arial" size="200"><field name="AdminName"/></font></paragraph><paragraph indent="0" align="center"><tabPositions><tabStop position="2880"/></tabPositions></paragraph><paragraph indent="0" align="center"><tabPositions><tabStop position="2880"/></tabPositions><font face="Arial" size="200" color="006A00"><b>Sign up as a team or individually.  If you sign up individually, you will be placed on a team.</b></font></paragraph>`,
  T4: `<paragraph indent="0" align="left"><tabPositions><tabStop position="2880"/></tabPositions></paragraph><table indent="0"><row><cell width="2160"><division indent="0" align="left"><font color="000000"><b>Registration:</b></font></division></cell><cell width="1785"></cell><cell width="3315"><division indent="0" align="left"><font color="C10000"><b><field name="League"/></b></font></division></cell><cell width="3810"><division indent="0" align="left"><font color="C10000">Due date:</font><font color="C10000"><b> April 28, 2008</b></font></division></cell></row><row><cell width="2160"></cell><cell width="1785"></cell><cell width="3315"><division indent="0" align="left"><font><field name="AdminAdrss"/></font></division></cell><cell width="3810"></cell></row><row><cell width="2160"></cell><cell width="1785"></cell><cell width="3315"><division indent="0" align="left"><font><field name="AdminsCity"/></font><font>, </font><font><field name="AdminState"/></font><sp/><sp/><font><field name="AdminsZIP"/></font></division></cell><cell width="3810"></cell></row><row><cell width="2160"></cell><cell width="1785"></cell><cell width="3315"></cell><cell width="3810"><division indent="0" align="left"><font color="FF0000">Cost per player: </font><font color="FF0000"><b>$</b></font><font color="FF0000"><b><field name="SignupFeeForIndividual"/></b></font><sp/></division></cell></row><row><cell width="2160"></cell><cell width="1785"></cell><cell width="3315"><division indent="0" align="left"><font size="320" color="FF0000"><field name="PaymentStatus"/></font></division></cell><cell width="3810"></cell></row></table>`,
};

export function registrationTextToXml(item, formName) {
  if (formName !== "Registration") return null;
  return REGISTRATION_TEXT_XML[item.label] ?? null;
}
