//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TawalaTest.BugTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TawalaTest.BugTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;project name=&quot;Untitled&quot; themePath=&quot;default&quot; format=&quot;1.4&quot;&gt;
        ///&lt;documents&gt;
        ///&lt;document name=&quot;Document 1&quot;&gt;
        ///&lt;xmlData&gt;
        ///&lt;paragraph indent=&quot;0&quot; align=&quot;left&quot;&gt;&lt;tabPositions&gt;&lt;tabStop position=&quot;720&quot;/&gt;&lt;/tabPositions&gt;&lt;/paragraph&gt;
        ///&lt;/xmlData&gt;
        ///&lt;/document&gt;
        ///&lt;/documents&gt;
        ///&lt;/project&gt;.
        /// </summary>
        internal static string ProjectXmlDocumentEmpty296 {
            get {
                return ResourceManager.GetString("ProjectXmlDocumentEmpty296", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;project name=&quot;Untitled&quot; themePath=&quot;default&quot; format=&quot;1.4&quot;&gt;
        ///&lt;forms&gt;
        ///&lt;form name=&quot;Form 1&quot; startPoint=&quot;true&quot; themePath=&quot;default&quot;&gt;
        ///&lt;items&gt;
        ///&lt;fib label=&quot;Q1&quot;&gt;&lt;paragraph indent=&quot;0&quot; align=&quot;left&quot;&gt;&lt;tabPositions&gt;&lt;tabStop position=&quot;144&quot;/&gt;&lt;/tabPositions&gt;&lt;font face=&quot;Arial&quot; size=&quot;200&quot; color=&quot;000000&quot;&gt;[Replace this with your question. Underscores create blanks.] &lt;/font&gt;&lt;blank label=&quot;a&quot; length=&quot;10&quot; required=&quot;false&quot;/&gt;&lt;/paragraph&gt;&lt;/fib&gt;
        ///&lt;/items&gt;
        ///&lt;/form&gt;
        ///&lt;/forms&gt;
        ///&lt;documents&gt;
        ///&lt;docu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjectXmlDocumentWithFibField296 {
            get {
                return ResourceManager.GetString("ProjectXmlDocumentWithFibField296", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;project name=&quot;Untitled&quot; themePath=&quot;default&quot; format=&quot;1.4&quot;&gt;
        ///&lt;processes&gt;
        ///&lt;process name=&quot;Process 1&quot;&gt;
        ///&lt;set field=&quot;MyVariable&quot; arithmeticAsText=&quot;false&quot;&gt;
        ///&lt;string value=&quot;1&quot;/&gt;
        ///&lt;/set&gt;
        ///&lt;/process&gt;
        ///&lt;/processes&gt;
        ///&lt;documents&gt;
        ///&lt;document name=&quot;Document 1&quot;&gt;
        ///&lt;xmlData&gt;
        ///&lt;paragraph indent=&quot;0&quot; align=&quot;left&quot;&gt;&lt;tabPositions&gt;&lt;tabStop position=&quot;720&quot;/&gt;&lt;/tabPositions&gt;&lt;font face=&quot;Arial&quot; size=&quot;200&quot; color=&quot;000000&quot;&gt;&lt;field name=&quot;MyVariable&quot;/&gt;&lt;/font&gt;&lt;/paragraph&gt;
        ///&lt;/xmlData&gt;
        ///&lt;/document&gt;
        ///&lt;/do [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjectXmlDocumentWithVariableField296 {
            get {
                return ResourceManager.GetString("ProjectXmlDocumentWithVariableField296", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\uc1\deff0{\fonttbl
        ///{\f0\fswiss\fcharset0\fprq2 Arial;}
        ///{\f1\froman\fcharset2\fprq2 Symbol;}}
        ///{\colortbl;\red0\green0\blue0;\red255\green255\blue255;}
        ///{\stylesheet{\s0\itap0\f0\fs24 [Normal];}{\*\cs10\additive Default Paragraph Font;}}
        ///{\*\generator TX_RTF32 12.0.500.502;}
        ///\deftab1134\paperw12240\paperh15840\margl720\margt720\margr720\margb720\notabind\pard\itap0\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\tx9360\tx10080\plain\f0\fs20{\*\tx [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RtfWithFibField296 {
            get {
                return ResourceManager.GetString("RtfWithFibField296", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\uc1\deff0{\fonttbl
        ///{\f0\fswiss\fcharset0\fprq2 Arial;}
        ///{\f1\froman\fcharset2\fprq2 Symbol;}}
        ///{\colortbl;\red0\green0\blue0;\red255\green255\blue255;}
        ///{\stylesheet{\s0\itap0\f0\fs24 [Normal];}{\*\cs10\additive Default Paragraph Font;}}
        ///{\*\generator TX_RTF32 12.0.500.502;}
        ///\deftab1134\paperw12240\paperh15840\margl720\margt720\margr720\margb720\notabind\pard\itap0\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\tx9360\tx10080\plain\f0\fs20\par\t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RtfWithTable296 {
            get {
                return ResourceManager.GetString("RtfWithTable296", resourceCulture);
            }
        }
    }
}
