//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3521
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tawala.Functions.Runtime.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tawala.Functions.Runtime.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //
        ///// Copyright © 2005-${YEAR} Tawala Systems, Inc. All rights reserved.
        /////
        ///using System;
        ///using System.ComponentModel;
        ///using System.Reflection;
        ///using System.Resources;
        ///using System.Runtime.InteropServices;
        ///using System.Runtime.CompilerServices;
        ///
        ///[assembly: AssemblyCompany(&quot;Tawala Systems, Inc&quot;)]
        ///[assembly: AssemblyProduct(&quot;Tawala&quot;)]
        ///[assembly: AssemblyCopyright(&quot;© 2005-${YEAR} Tawala Systems, Inc. All rights reserved.&quot;)]
        ///[assembly: AssemblyVersion(&quot;${ASSEMBLYVERSION}&quot;)]
        ///[assembly: AssemblyInfo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ASSEMBLY_INFO {
            get {
                return ResourceManager.GetString("ASSEMBLY_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    internal sealed class CategoryInfo : ICategoryInfo
        ///    {
        ///        #region ICategoryInfo Members
        ///
        ///        public string Name { get { return name; } }
        ///
        ///        public IFunctionInfoCollection Functions { get { return functionInfo; } }
        ///
        ///        public XPathNavigator Xml { get { return navCategory.Clone(); } }
        ///
        ///        #endregion
        ///
        ///        public override string ToString()
        ///        {
        ///            return Name;
        ///        }
        ///
        ///        #region PRIVATE
        ///
        ///        private readonly FunctionInfoCollection [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CATEGORY_INFO {
            get {
                return ResourceManager.GetString("CATEGORY_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   
        ///    internal sealed class CategoryInfoCollection : Collection&lt;ICategoryInfo&gt;, ICategoryInfoCollection
        ///    {
        ///        private readonly Dictionary&lt;string, ICategoryInfo&gt; nameToInfo = new Dictionary&lt;string, ICategoryInfo&gt;();
        ///
        ///        #region ICategoryInfoCollection Members
        ///
        ///        public ICategoryInfo this[string name] { get { return nameToInfo[name]; } }
        ///
        ///        public bool Contains(string name)
        ///        {
        ///            return nameToInfo.ContainsKey(name);
        ///        }
        ///
        ///        #endregion
        ///
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CATEGORY_INFO_COLLECTION {
            get {
                return ResourceManager.GetString("CATEGORY_INFO_COLLECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //
        ///// Copyright © 2005-${YEAR} Tawala Systems, Inc. All rights reserved.
        /////
        ///using System;
        ///using System.Collections;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.ComponentModel;
        ///using System.Data;
        ///using System.Diagnostics;
        ///using System.IO;
        ///using System.Reflection;
        ///using System.Resources;
        ///using System.Text;
        ///using System.Xml.XPath;
        ///using System.Runtime.InteropServices;
        ///using System.Runtime.CompilerServices;
        ///
        ///using Tawala.Projects;
        ///using Tawala.Projects [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CODE_PREAMBLE {
            get {
                return ResourceManager.GetString("CODE_PREAMBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		public class __composite_${PNAME} : CompositeParameterBase
        ///		{
        ///			public  __composite_${PNAME}()
        ///			{
        ///				Parameters = LookupParameterInfo(GetType());
        ///				Properties = new PropertyCollection&lt;__composite_${PNAME}&gt;(this, Parameters);	
        ///			}
        ///		
        ///		    ${PROPERTIES}
        ///		}
        ///		
        ///		public class __composite_collection_${PNAME} : CompositeParameterCollectionBase&lt;__composite_${PNAME}&gt;
        ///		{				
        ///			protected override void OnListChanged(ListChangedEventArgs e)
        ///			{
        ///				base.OnListChanged(e);
        ///				
        ///				if (F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string COMPOSITE_PARAMETER {
            get {
                return ResourceManager.GetString("COMPOSITE_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    public abstract class CompositeParameterBase : ICompositeParameter
        ///    {
        ///        private const string xmlFormat = &quot;&lt;{0}&gt;{1}&lt;/{0}&gt;&quot;;
        ///        protected IParameterInfoCollection Parameters;
        ///
        ///        #region ICompositeParameter Members
        ///
        ///        public event PropertyChangedEventHandler PropertyChanged;
        ///
        ///        public string ToValueXml()
        ///        {
        ///            StringBuilder sbItems = new StringBuilder();
        ///
        ///            for (int i = 0; i &lt; Parameters.Count; ++i)
        ///            {
        ///                obj [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string COMPOSITE_PARAMETER_BASE {
            get {
                return ResourceManager.GetString("COMPOSITE_PARAMETER_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    public abstract class CompositeParameterCollectionBase&lt;T&gt; : BindingList&lt;ICompositeParameter&gt;, ICompositeParameterCollection
        ///        where T : CompositeParameterBase, ICompositeParameter, new()
        ///    {
        ///        #region ICompositeParameterCollection Members
        ///
        ///        public override string ToString()
        ///        {
        ///            StringBuilder sbXml = new StringBuilder();
        ///
        ///            foreach (ICompositeParameter composite in this)
        ///            {
        ///                sbXml.Append(composite.ToString());
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string COMPOSITE_PARAMETER_COLLECTION_BASE {
            get {
                return ResourceManager.GetString("COMPOSITE_PARAMETER_COLLECTION_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///	public sealed class ${CLASSNAMEV} : Function
        ///	{
        ///		public ${CLASSNAMEV}() 
        ///		{
        ///			Properties = new PropertyCollection&lt;${CLASSNAMEV}&gt;(this, functionInfo.Parameters);
        ///		}
        ///		
        ///		${PROPERTIES}
        ///		
        ///  		public override IFunctionInfo Info { get { return functionInfo; } }
        ///  		  		
        ///		public override void BeginEdit()
        ///  		{
        ///  		    ForwardPropertyChanged += forward;
        ///  		}
        ///  		
        ///  		public override void EndEdit()
        ///  		{
        ///   		    ForwardPropertyChanged -= forward;
        ///  		}
        ///  		
        ///  		private static event P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FUNCTION {
            get {
                return ResourceManager.GetString("FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	
        ///	internal sealed class ${CLASSNAMEV}_FunctionInfo : IFunctionInfo
        ///	{
        ///		public IFunction CreateInstance() { return FunctionFactory.CreateInstance&lt;${CLASSNAMEV}&gt;(); }
        ///
        ///		public IParameterInfoCollection Parameters { get { return parameters; } }
        ///
        ///		public string Id { get { return &quot;${FID}&quot;; } }
        ///
        ///		public string Name { get { return &quot;${FNAME}&quot;;  } }
        ///
        ///		public string Description { get { return description; } }
        ///
        ///		public string Version { get { return &quot;${FVERSION}&quot;; } }
        ///
        ///		public Type Type { get { re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FUNCTION_INFO {
            get {
                return ResourceManager.GetString("FUNCTION_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    internal sealed class FunctionInfoCollection : Collection&lt;IFunctionInfo&gt;, IFunctionInfoCollection
        ///    {
        ///        private readonly Dictionary&lt;string, IFunctionInfo&gt; idToInfo = new Dictionary&lt;string, IFunctionInfo&gt;();
        ///        private readonly Dictionary&lt;Type, IFunctionInfo&gt; typeToInfo = new Dictionary&lt;Type, IFunctionInfo&gt;();
        ///
        ///        #region IFunctionInfoCollection Members
        ///
        ///        public IFunctionInfo this[string id] { get { return idToInfo[id]; } }
        ///
        ///        public IFunctionInfo this[Type type] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FUNCTION_INFO_COLLECTION {
            get {
                return ResourceManager.GetString("FUNCTION_INFO_COLLECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	public sealed class FunctionRepository : IFunctionRepository
        ///	{
        ///        public IFunctionInfoCollection Functions { get { return functionInfoCollection; } }
        ///        public ICategoryInfoCollection Categories  { get { return categoryInfoCollection; } }
        ///
        ///        public XPathNavigator Xml { get { return navigator.Clone(); } }
        ///
        ///		public Assembly GeneratedAssembly { get { return Assembly.GetExecutingAssembly(); }	}
        ///		public string Signature	{ get { return &quot;${REPOSITORYSIGNATURE}&quot;; } }
        ///		public string Cre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FUNCTION_REPOSITORY {
            get {
                return ResourceManager.GetString("FUNCTION_REPOSITORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		private ${TYPE} prop_${FNAME}${FASSIGN};
        ///
        ///        [ParameterProperty(&quot;${GID}&quot;, typeof(${TYPE}), typeof(${TYPE}))]
        ///		public ${TYPE} ${PNAME}
        ///		{
        ///			get	{ return prop_${FNAME};	}
        ///			set
        ///			{
        ///				if (prop_${FNAME} != value) { prop_${FNAME} = value; NotifyChanged(&quot;${PNAME}&quot;);	}
        ///			}
        ///		}.
        /// </summary>
        internal static string PARAMETER {
            get {
                return ResourceManager.GetString("PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 			
        ///		private PARAMETER_CONTAINER parameter_container;
        ///		
        ///		public class PARAMETER_CONTAINER : PARAMETER_CONTAINER_BASE
        ///		{
        ///			public PARAMETER_CONTAINER(object owner) : base(owner)
        ///			{
        ///			}
        ///			
        ///			${PROPERTIES}
        ///		}
        ///.
        /// </summary>
        internal static string PARAMETER_CONTAINER {
            get {
                return ResourceManager.GetString("PARAMETER_CONTAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 			
        ///		public class PARAMETER_CONTAINER_BASE : INotifyPropertyChanged
        ///		{
        ///			public event PropertyChangedEventHandler PropertyChanged;
        ///			
        ///			protected void Notify(string pname)
        ///			{
        ///				if (PropertyChanged != null)
        ///				{
        ///					PropertyChanged(this, new PropertyChangedEventArgs(pname));
        ///				}
        ///			}
        ///	
        ///			protected PARAMETER_CONTAINER_BASE(object owner)
        ///			{
        ///				this.owner = owner;
        ///			}
        ///			
        ///			protected readonly object owner;			
        ///		}
        ///	}
        ///.
        /// </summary>
        internal static string PARAMETER_CONTAINER_BASE {
            get {
                return ResourceManager.GetString("PARAMETER_CONTAINER_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    internal class PropertyCollection&lt;T&gt; : IPropertyCollection where T : class
        ///    {
        ///        private const BindingFlags bindingFlags = BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly;
        ///        private static int count;
        ///        private static IParameterInfoCollection parameterInfoCollection;
        ///        private static readonly Collection&lt;string&gt; ids = new Collection&lt;string&gt;();
        ///        private static readonly Collection&lt;PropertyInfo&gt; properties = new Collection&lt;PropertyInfo&gt;();
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PROPERTY_COLLECTION {
            get {
                return ResourceManager.GetString("PROPERTY_COLLECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	internal static class Utility
        ///	{
        ///		internal static FunctionFilterConditions CreateDefaultFunctionFilterConditions()	
        ///		{
        ///			FunctionFilterConditions conditions = new FunctionFilterConditions();
        ///			conditions.Conditions = new Conditions();
        ///			return conditions;
        ///		}	
        ///		
        ///		internal static FunctionParameterConditions CreateDefaultFunctionParameterConditions()
        ///		{
        ///			return new FunctionParameterConditions();
        ///		}
        ///		
        ///		internal static Conditions CreateDefaultConditions()
        ///		{
        ///			return new Conditio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UTILITY {
            get {
                return ResourceManager.GetString("UTILITY", resourceCulture);
            }
        }
    }
}
