//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TawalaDesigner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TawalaDesigner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tawala Designer - Build 1.0.32.
        /// </summary>
        internal static string ApplicationTitlePrefix {
            get {
                return ResourceManager.GetString("ApplicationTitlePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Fill in the Blank questions are selected in the active form. You may apply the style to all Fill in the Blank questions in the project..
        /// </summary>
        internal static string ApplyStyleToAllFIBItems {
            get {
                return ResourceManager.GetString("ApplyStyleToAllFIBItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Multiple Choice questions are selected in the active form. You may apply the style to all Multiple Choice questions in the project..
        /// </summary>
        internal static string ApplyStyleToAllMCQItems {
            get {
                return ResourceManager.GetString("ApplyStyleToAllMCQItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Text items are selected in the active form. You may apply the style to all Text items in the project..
        /// </summary>
        internal static string ApplyStyleToAllTextItems {
            get {
                return ResourceManager.GetString("ApplyStyleToAllTextItems", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CascadeWindows {
            get {
                object obj = ResourceManager.GetObject("CascadeWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project deployment failed:.
        /// </summary>
        internal static string DeployFailure {
            get {
                return ResourceManager.GetString("DeployFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to view selected Form.
        /// </summary>
        internal static string DeploymentLinkText {
            get {
                return ResourceManager.GetString("DeploymentLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Project was successfully deployed..
        /// </summary>
        internal static string DeploySuccess {
            get {
                return ResourceManager.GetString("DeploySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may select a Form from the list below and click on the link to invoke it..
        /// </summary>
        internal static string DeploySuccessMessage {
            get {
                return ResourceManager.GetString("DeploySuccessMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Document_New {
            get {
                object obj = ResourceManager.GetObject("Document_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_Copy {
            get {
                object obj = ResourceManager.GetObject("Edit_Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_Cut {
            get {
                object obj = ResourceManager.GetObject("Edit_Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_Delete {
            get {
                object obj = ResourceManager.GetObject("Edit_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_Paste {
            get {
                object obj = ResourceManager.GetObject("Edit_Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Folder_Open {
            get {
                object obj = ResourceManager.GetObject("Folder_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form_New {
            get {
                object obj = ResourceManager.GetObject("Form_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help_About {
            get {
                object obj = ResourceManager.GetObject("Help_About", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tawala Project Files (*.tawala)|*.tawala|Tawala XML Files (*.xml)|*.xml.
        /// </summary>
        internal static string OpenProjectFilter {
            get {
                return ResourceManager.GetString("OpenProjectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid blank label.
        /// </summary>
        internal static string OptionsInvalidBlankLabel {
            get {
                return ResourceManager.GetString("OptionsInvalidBlankLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid label.
        /// </summary>
        internal static string OptionsInvalidItemLabel {
            get {
                return ResourceManager.GetString("OptionsInvalidItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid question label.
        /// </summary>
        internal static string OptionsInvalidQuestionLabel {
            get {
                return ResourceManager.GetString("OptionsInvalidQuestionLabel", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Process_New {
            get {
                object obj = ResourceManager.GetObject("Process_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Project_Deploy {
            get {
                object obj = ResourceManager.GetObject("Project_Deploy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Project_Manager {
            get {
                object obj = ResourceManager.GetObject("Project_Manager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Project_New {
            get {
                object obj = ResourceManager.GetObject("Project_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Project_Save {
            get {
                object obj = ResourceManager.GetObject("Project_Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tawala.
        /// </summary>
        internal static string ProjectExt {
            get {
                return ResourceManager.GetString("ProjectExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tawala Project Files (*.tawala)|*.tawala.
        /// </summary>
        internal static string SaveProjectFilter {
            get {
                return ResourceManager.GetString("SaveProjectFilter", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap StartupTasksViewBackground {
            get {
                object obj = ResourceManager.GetObject("StartupTasksViewBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TileWindowsHorizontally {
            get {
                object obj = ResourceManager.GetObject("TileWindowsHorizontally", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TileWindowsVertically {
            get {
                object obj = ResourceManager.GetObject("TileWindowsVertically", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Functions....
        /// </summary>
        internal static string UpdatingFunctions {
            get {
                return ResourceManager.GetString("UpdatingFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Shared Data Sources Data....
        /// </summary>
        internal static string UpdatingSharedDataSources {
            get {
                return ResourceManager.GetString("UpdatingSharedDataSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Project Themes....
        /// </summary>
        internal static string UpdatingThemes {
            get {
                return ResourceManager.GetString("UpdatingThemes", resourceCulture);
            }
        }
    }
}
